package com.example.stoycho.phonebook.communicationClasses.commands;

public class AllCommands {
    public static final int COMMAND_LOGIN                               = 1; //working
    public static final int COMMAND_LOG_OUT                             = 2; //working
    public static final int COMMAND_CLIENT_DATA                         = 3; //working
    public static final int COMMAND_GET_USER_RIGHTS                     = 4; //working
    public static final int COMMAND_GET_BALANCE_IN_MAIN_CURR            = 5; //working
    public static final int COMMAND_GET_TRANSACTIONS_LIST               = 6; //working
    public static final int COMMAND_GET_ALL_BALANCES                    = 7; //working
    public static final int COMMAND_GET_TRANSACTION_DETAILS             = 8; //working
    public static final int COMMAND_GET_CLIENT_CARDS                    = 9; //working
    public static final int COMMAND_GET_CARDS_CONTROL                   = 10; //working
    public static final int COMMAND_LOGIN_DATA                          = 11; //working
    public static final int COMMAND_GET_TRANSACTION_FILTERS             = 12;
    public static final int COMMAND_SAVE_CARD_CONTROL                   = 13; //working
    public static final int COMMAND_SAVE_CARD_LIMITS                    = 14; //working
    public static final int COMMAND_GET_TARIFF_LIMITS                   = 15; //working
    public static final int COMMAND_UPDATE_CARD_STATUS                  = 16; //working
    public static final int COMMAND_GET_RECENT_NOTIFICATION             = 17;
    public static final int COMMAND_LINK_CARD_PARAMS                    = 18; //working
    public static final int COMMAND_REQUEST_FOR_SMS                     = 19; //working
    public static final int COMMAND_CHECK_SMS                           = 20; //working
    public static final int COMMAND_CREATE_ACCOUNT                      = 21; //working
    public static final int COMMAND_GET_ALL_CURRENCIES                  = 22; //working
    public static final int COMMAND_DELETE_ACCOUNT                      = 23; //working
    public static final int COMMAND_REORDER_ACCOUNTS                    = 24;
    public static final int COMMAND_GET_CARDS_LIMITS                    = 25; //working
    public static final int COMMAND_EDIT_PUSH_DATA                      = 26;
    public static final int COMMAND_GET_ALL_CLIENTS_IBANS               = 27;
    public static final int COMMAND_READ_NOTIFICATIONS                  = 28; //working
    public static final int COMMAND_SET_WALLET_DEFAULT                  = 29;
    public static final int COMMAND_CHANGE_WALLET                       = 30; //working
    public static final int COMMAND_USER_WALLETS_DETAIL                 = 31;
    public static final int COMMAND_GET_WALLETS_LIST                    = 32; //working
    public static final int COMMAND_GET_NOTIFICATIONS_LIST              = 33; //working
    public static final int COMMAND_GET_SYSTEM_NOTIFICATION_MSG         = 34;
    public static final int COMMAND_SET_ACCOUNT_ACTIVE_OR_BLOCKED       = 35; //working
    public static final int COMMAND_SYNC_CONTACTS                       = 36; //working
    public static final int COMMAND_EDIT_NOTIFICATIONS_SETTINGS         = 37; //working
    public static final int COMMAND_ACTIVATE_CARD_OR_TAG                = 38; //working
    public static final int COMMAND_SEND_CONF_CODE                      = 39;
    public static final int COMMAND_CHECK_EGN                           = 40;
    public static final int COMMAND_CHECK_USER                          = 41; //working
    public static final int COMMAND_GET_C_WALLET_NUMBER                 = 42;
    public static final int COMMAND_GET_ALL_EXCHANGE_RATES              = 43;
    public static final int COMMAND_SYNC_CONTACTS_BY_MAIL               = 44; //working
    public static final int COMMAND_CHECK_ACCOUNT_NUMBER                = 45;
    public static final int COMMAND_MAIL_REG                            = 46;
    public static final int COMMAND_GET_LAST_TRANSFERS                  = 47;
    public static final int COMMAND_LINKED_CARDS_LIST                   = 48; //working
    public static final int COMMAND_SEND_MONEY                          = 49; //working
    public static final int COMMAND_EXCHANGE_MONEY                      = 50; //working
    public static final int COMMAND_ADD_LINK_CARD                       = 51; //working
    public static final int COMMAND_DELETE_LINK_CARD                    = 52; //working
    public static final int COMMAND_FUND_FROM_LINK_CARD                 = 53; //working
    public static final int COMMAND_VERIFY_CARD                         = 54; //working
    public static final int COMMAND_SEND_CONFIRMATION_CODE              = 55; //working
    public static final int COMMAND_GSM_REG                             = 56; //working
    public static final int COMMAND_GET_ALL_ACC_TRANSACTIONS_LISTS      = 57; //working
    public static final int COMMAND_FIND_LEUPOST_WALLET                 = 58; //working
    public static final int COMMAND_SEND_MONEY_TO_LEUPOST               = 59; //working
    public static final int COMMAND_SEND_BANK_TRANSFER                  = 60; //working
    public static final int COMMAND_GET_HISTORY_TRANSFER                = 61; //working
    public static final int COMMAND_GET_IBAN_INFO                       = 62; //working
    public static final int COMMAND_GET_CARDS_NOTIFICATIONS             = 63; //working
    public static final int COMMAND_GET_BALANCE_IN_DIFFERENT_CURRENCIES = 64; //working
    public static final int COMMAND_GET_IPAY_FUNDING_MERCHANTS          = 65; //working
    public static final int COMMAND_GET_URL                             = 66; //working
    public static final int COMMAND_ORDER_PREPAID_CARD                  = 67;
    public static final int COMMAND_PREPAID_CARD_ORDERS_LIST            = 68;
    public static final int COMMAND_GET_PREPAID_CARD_DESIGNS            = 69;
    public static final int COMMAND_GET_PREPAID_OPERATORS               = 70;
    public static final int COMMAND_GET_PREPAID_OPERATOR_PRODUCTS       = 71;
    public static final int COMMAND_GET_PREPAID_OPERATOR_COUNTRIES      = 72;
    public static final int COMMAND_PROCESS_PREPAID_PAYMENT             = 73;
    public static final int COMMAND_GET_USED_PREPAID_OPERATORS          = 74;
    public static final int COMMAND_GET_ALL_AND_USED_PREPAID_OPERATORS  = 75;
    public static final int COMMAND_GET_EXTENDED_CARDS                  = 76;
    public static final int COMMAND_GET_PREPAID_PAYMENTS_HISTORY        = 77;
    public static final int COMMAND_GET_ACTIVE_COUNTRIES                = 78;
    public static final int COMMAND_GET_PREPAID_PAYMENT_DETAILS         = 79;
}
